### ISSUE TITLE
Option to control literal character escapes

### ISSUE THREAD

**Issue by sehrgut** [Shakeskeyboarde/slashes#2]
If set options.n = false, I would expect the sequence "\n" to be retained in the output. Instead, the sequence "\n" is interpreted as simply any other non-metacharacter, and replaced with "n". This behaviour should be switchable.

**Comment by Shakeskeyboarde** [comment]
Fixed in v3. Options have changed, but this can controlled using the `getUnescaped` option of the `removeSlashes(…, { getUnescaped })` function.
